version: '3.8'

services:
  steel-automation:
    build: .
    image: steel-automation:latest
    container_name: steel-automation-app
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - STEEL_CONFIG_PATH=/app/config/settings.yaml
    command: python main_steel.py --data data/steel_orders.csv --output reports
    depends_on:
      - redis
      - postgres
    networks:
      - steel-network

  redis:
    image: redis:7-alpine
    container_name: steel-automation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - steel-network

  postgres:
    image: postgres:15-alpine
    container_name: steel-automation-db
    environment:
      POSTGRES_DB: steel_automation
      POSTGRES_USER: steel_user
      POSTGRES_PASSWORD: steel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - steel-network

volumes:
  redis_data:
  postgres_data:

networks:
  steel-network:
    driver: bridge
