# Email Templates Configuration

templates:
  
  # Booking Confirmation Email
  booking_confirmation:
    subject: "Flight Booking Confirmation - {pnr}"
    html_body: |
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="UTF-8">
          <title>Flight Booking Confirmation</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { text-align: center; color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 20px; margin-bottom: 30px; }
              .booking-details { background-color: #ecf0f1; padding: 20px; border-radius: 5px; margin: 20px 0; }
              .detail-row { margin: 10px 0; }
              .label { font-weight: bold; color: #34495e; }
              .value { color: #2c3e50; }
              .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 12px; }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="header">
                  <h1>✈️ Flight Booking Confirmed</h1>
                  <p>Your reservation has been successfully processed</p>
              </div>
              
              <div class="booking-details">
                  <h2>Booking Details</h2>
                  <div class="detail-row">
                      <span class="label">PNR:</span> 
                      <span class="value">{pnr}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Passenger:</span> 
                      <span class="value">{passenger}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Route:</span> 
                      <span class="value">{origin} → {destination}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Fare:</span> 
                      <span class="value">${fare:.2f}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Status:</span> 
                      <span class="value">{status}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Travel Date:</span> 
                      <span class="value">{travel_date}</span>
                  </div>
              </div>
              
              <div class="footer">
                  <p>Thank you for choosing our service!</p>
                  <p>This is an automated message from the Flight Booking Automation System.</p>
              </div>
          </div>
      </body>
      </html>
    
    text_body: |
      ✈️ FLIGHT BOOKING CONFIRMATION ✈️
      
      Dear {passenger},
      
      Your flight booking has been confirmed!
      
      BOOKING DETAILS:
      ================
      PNR: {pnr}
      Passenger: {passenger}
      Route: {origin} → {destination}
      Fare: ${fare:.2f}
      Status: {status}
      Travel Date: {travel_date}
      
      Thank you for choosing our service!
      
      This is an automated message from the Flight Booking Automation System.
  
  # Booking Cancellation Email
  booking_cancellation:
    subject: "Flight Booking Cancelled - {pnr}"
    html_body: |
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="UTF-8">
          <title>Flight Booking Cancellation</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { text-align: center; color: #e74c3c; border-bottom: 2px solid #e74c3c; padding-bottom: 20px; margin-bottom: 30px; }
              .booking-details { background-color: #fdf2f2; padding: 20px; border-radius: 5px; margin: 20px 0; border: 1px solid #e74c3c; }
              .detail-row { margin: 10px 0; }
              .label { font-weight: bold; color: #34495e; }
              .value { color: #2c3e50; }
              .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 12px; }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="header">
                  <h1>❌ Flight Booking Cancelled</h1>
                  <p>Your reservation has been cancelled</p>
              </div>
              
              <div class="booking-details">
                  <h2>Cancelled Booking Details</h2>
                  <div class="detail-row">
                      <span class="label">PNR:</span> 
                      <span class="value">{pnr}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Passenger:</span> 
                      <span class="value">{passenger}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Route:</span> 
                      <span class="value">{origin} → {destination}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Refund Amount:</span> 
                      <span class="value">${fare:.2f}</span>
                  </div>
              </div>
              
              <div class="footer">
                  <p>If you have any questions, please contact our customer service.</p>
                  <p>This is an automated message from the Flight Booking Automation System.</p>
              </div>
          </div>
      </body>
      </html>
    
    text_body: |
      ❌ FLIGHT BOOKING CANCELLED ❌
      
      Dear {passenger},
      
      Your flight booking has been cancelled.
      
      CANCELLED BOOKING DETAILS:
      ==========================
      PNR: {pnr}
      Passenger: {passenger}
      Route: {origin} → {destination}
      Refund Amount: ${fare:.2f}
      
      If you have any questions, please contact our customer service.
      
      This is an automated message from the Flight Booking Automation System.

  # Processing Error Email
  processing_error:
    subject: "Flight Booking Processing Error - {pnr}"
    html_body: |
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="UTF-8">
          <title>Flight Booking Processing Error</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
              .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { text-align: center; color: #f39c12; border-bottom: 2px solid #f39c12; padding-bottom: 20px; margin-bottom: 30px; }
              .error-details { background-color: #fdf6e3; padding: 20px; border-radius: 5px; margin: 20px 0; border: 1px solid #f39c12; }
              .detail-row { margin: 10px 0; }
              .label { font-weight: bold; color: #34495e; }
              .value { color: #2c3e50; }
              .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 12px; }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="header">
                  <h1>⚠️ Processing Error</h1>
                  <p>There was an issue processing your booking</p>
              </div>
              
              <div class="error-details">
                  <h2>Error Details</h2>
                  <div class="detail-row">
                      <span class="label">PNR:</span> 
                      <span class="value">{pnr}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Error:</span> 
                      <span class="value">{error_message}</span>
                  </div>
                  <div class="detail-row">
                      <span class="label">Next Steps:</span> 
                      <span class="value">Our team has been notified and will resolve this issue shortly.</span>
                  </div>
              </div>
              
              <div class="footer">
                  <p>We apologize for the inconvenience.</p>
                  <p>This is an automated message from the Flight Booking Automation System.</p>
              </div>
          </div>
      </body>
      </html>
    
    text_body: |
      ⚠️ FLIGHT BOOKING PROCESSING ERROR ⚠️
      
      Dear Customer,
      
      There was an issue processing your booking.
      
      ERROR DETAILS:
      ==============
      PNR: {pnr}
      Error: {error_message}
      
      Our team has been notified and will resolve this issue shortly.
      
      We apologize for the inconvenience.
      
      This is an automated message from the Flight Booking Automation System.
