# Steel Industry Email Templates

order_confirmation:
  subject: "Steel Order Confirmation - {order_id}"
  body: |
    Dear {customer_name},

    Thank you for your steel order. We are pleased to confirm the following details:

    ORDER DETAILS:
    Order ID: {order_id}
    Batch ID: {batch_id}
    Steel Grade: {steel_grade}
    Steel Type: {steel_type}
    Dimensions: {thickness}mm x {width}mm x {length}mm
    Weight: {weight:,.1f} kg
    Total Price: ${total_price:,.2f}

    PRODUCTION DETAILS:
    Production Line: {production_line}
    Expected Production Date: {production_date}
    Expected Delivery Date: {delivery_date}
    Quality Grade: {quality_grade}
    Warehouse: {warehouse}

    Your order is currently: {status}

    We will keep you updated on the progress of your order. Please contact us if you have any questions.

    Best regards,
    Steel Corporation Production Team
    Email: production@steelcorp.com
    Phone: 1-800-STEEL-01

production_update:
  subject: "Production Update - Order {order_id}"
  body: |
    Dear {customer_name},

    We would like to update you on the production status of your steel order:

    Order ID: {order_id}
    Current Status: {status}
    Production Line: {production_line}
    Quality Grade: {quality_grade}

    {status_message}

    Thank you for choosing Steel Corporation.

    Best regards,
    Production Team

quality_alert:
  subject: "Quality Alert - Order {order_id}"
  body: |
    Dear {customer_name},

    We need to inform you about a quality issue with your steel order:

    Order ID: {order_id}
    Quality Grade: {quality_grade}
    Issue: Quality grade below standard specifications

    Our quality control team is working to resolve this issue. We will contact you shortly with options including:
    - Rework to meet specifications
    - Replacement order
    - Partial refund

    We apologize for any inconvenience and appreciate your patience.

    Best regards,
    Quality Control Team

shipping_notification:
  subject: "Shipping Notification - Order {order_id}"
  body: |
    Dear {customer_name},

    Great news! Your steel order has been shipped and is on its way to you.

    ORDER DETAILS:
    Order ID: {order_id}
    Steel Grade: {steel_grade}
    Weight: {weight:,.1f} kg
    
    SHIPPING DETAILS:
    Shipped From: {warehouse}
    Expected Delivery: {delivery_date}
    Tracking Number: {tracking_number}

    Please ensure someone is available to receive the delivery on the scheduled date.

    Thank you for your business!

    Best regards,
    Logistics Team

delivery_confirmation:
  subject: "Delivery Confirmation - Order {order_id}"
  body: |
    Dear {customer_name},

    This email confirms that your steel order has been successfully delivered.

    Order ID: {order_id}
    Delivered on: {delivery_date}
    Delivered to: {delivery_address}
    Received by: {received_by}

    Please inspect the delivered materials and contact us within 48 hours if you notice any issues.

    We appreciate your business and look forward to serving you again.

    Best regards,
    Steel Corporation Customer Service

order_cancellation:
  subject: "Order Cancellation - {order_id}"
  body: |
    Dear {customer_name},

    We regret to inform you that your steel order has been cancelled.

    Order ID: {order_id}
    Cancellation Reason: {cancellation_reason}
    Refund Amount: ${refund_amount:,.2f}

    Your refund will be processed within 3-5 business days and credited back to your original payment method.

    If you have any questions about this cancellation, please contact our customer service team.

    We apologize for any inconvenience caused.

    Best regards,
    Customer Service Team

rework_notification:
  subject: "Rework Required - Order {order_id}"
  body: |
    Dear {customer_name},

    During quality inspection, we identified that your steel order requires rework to meet specifications.

    Order ID: {order_id}
    Quality Issue: {quality_issue}
    Rework Required: {rework_description}

    REVISED TIMELINE:
    Rework Start Date: {rework_start_date}
    New Expected Completion: {revised_completion_date}
    New Delivery Date: {revised_delivery_date}

    We will keep you updated on the rework progress. No additional charges will apply for this rework.

    We apologize for the delay and appreciate your patience.

    Best regards,
    Quality Control Team
