# Steel Industry Automation Configuration
steel_automation:
  # Data processing settings
  data_processing:
    batch_size: 100
    enable_vectorization: true
    parallel_processing: true
    max_workers: 4
    
  # Validation settings
  validation:
    strict_mode: false
    enable_business_rules: true
    log_warnings: true
    max_errors_per_order: 10
    
  # Email settings
  email:
    smtp_server: "smtp.steelcompany.com"
    smtp_port: 587
    use_tls: true
    sender_email: "automation@steelcompany.com"
    sender_name: "Steel Production Automation"
    rate_limit: 10  # emails per second
    retry_attempts: 3
    timeout: 30
    
  # Reporting settings
  reporting:
    include_detailed_logs: true
    generate_charts: true
    export_formats: ["csv", "json", "pdf"]
    archive_reports: true
    
  # Performance settings
  performance:
    enable_profiling: false
    memory_threshold_mb: 1000
    log_performance_metrics: true
    
  # Steel industry specific settings
  steel_standards:
    grade_validation: true
    dimensional_tolerance: 0.1  # percentage
    weight_tolerance: 0.05     # percentage
    quality_standards: ["ASTM", "ISO", "JIS"]
    
  # Production workflow
  production:
    default_lead_time_days: 14
    quality_check_required: true
    batch_tracking: true
    production_lines: 10
